# -----------------------
#
# Author: Daniel Fryer
# Date: 2023-02-23
#
# This script creates two sqlite databases:
#
# 1. variants
# 2. variants_dodgy
#
# Database 1 (variants) contains 4 tables:
# GENE, VARIANT, COMBINATION and PATIENT.
#
# Database 2 (variants_dodgy) contains 1 table:
# PATIENT_VARIANT
#
# In database 1, we use primary/foreign key pairs 
# to specify relationships between tables.
#
# In database 2, we avoid primary/foreign keys,
# and just insert everything into one table.
#
# The same dummy data is used in both databases.
#
# Database 1 (variants) is then 
# compared to database 2 (variants_dodgy).
#
# The comparison highlights why we prefer 
# database 1 over database 2.
#
# CAUTION:
# A lot of the data for this exercise was generated by ChatGPT. 
# It is NOT a real dataset.
#
# -----------------------

# See RSQLite tutorial here: 
# https://cran.r-project.org/web/packages/RSQLite/vignettes/RSQLite.html

install.packages("RSQLite")
library(RSQLite)

# We will also use these libraries (some are used by functions in functions.R)
library(readr)
library(glue)
library(tibble)
library(dplyr)
library(magrittr)

# We will use these helper functions too 
source("functions.R")

# -------------------------------------------------------------------------

# create an empty database and connect to it
con <- DBI::dbConnect(RSQLite::SQLite(), "data/variants.sqlite")

# execute the script create_variants_database.sql
# NOTE: if the database already exists, this will produce an error.
# you may want to delete data/variants.sqlite first.
execute_sql_script(con, "create_variants_database.sql")

# list the table name
DBI::dbListTables(con)

# take a look at the Gene table for example
gene <- dplyr::tbl(con, "Gene")
gene <- gene %>% dplyr::collect()

# This joins all the tables in the variants database
query <- '
SELECT P.patient_id, 
       G.name AS gene_name, V.name AS variant_name, 
       GV.comment,
       PGV.vaf, GV.pop_freq, 
       P.ethnicity, P.cancer_type
FROM Patient_Gene_variant PGV 
  RIGHT JOIN Gene_variant GV ON PGV.gene_variant_id = GV.gene_variant_id
  RIGHT JOIN Gene G ON GV.gene_id = G.gene_id
  RIGHT JOIN Variant V ON GV.variant_id = V.variant_id
  RIGHT JOIN Patient P ON PGV.patient_id = P.patient_id
'
one_table <- DBI::dbGetQuery(con, query) 

# disconnect from the variants database
DBI::dbDisconnect(con)

# create an empty variants_dodgy database
con <- DBI::dbConnect(RSQLite::SQLite(), "data/variants_dodgy.sqlite")

# add table to the database
DBI::dbWriteTable(con, "patient_variants", one_table)

# disconnect from the variants_dodgy database
DBI::dbDisconnect(con)

# write the patient_variants table as a csv
write.csv(one_table, "data/patient_variants.csv")

# Example -----------------------------------------------------------------

con1 <- DBI::dbConnect(RSQLite::SQLite(), "data/variants_dodgy.sqlite")
con2 <- DBI::dbConnect(RSQLite::SQLite(), "data/variants.sqlite")

# The variants (like G13D) always have pattern <letter><number><letter>.
# Final all the variants starting with D. Count the number of times a patient
# has had that variant.

# query1 and query2 both achieve the same thing, just on different database
# structures. 

# This one uses variants_dodgy database. It makes use of LIKE
query1 <- "
SELECT COUNT(*) AS num
FROM patient_variants
WHERE variant_name LIKE 'D%'
"

# # This one uses variants database. It makes use of JOIN and '='
query2 <- "
SELECT COUNT(*) AS num
FROM Patient_Gene_variant PGV 
   JOIN Gene_Variant GV ON PGV.gene_variant_id = GV.gene_variant_id
   JOIN Variant V ON GV.variant_id = V.variant_id
WHERE V.change_from = 'D'
"

result1 <- DBI::dbGetQuery(con1, query1)
result2 <- DBI::dbGetQuery(con2, query2)

DBI::dbDisconnect(con1)
DBI::dbDisconnect(con2)

# Auto-generated primary key (AUTOINCREMENT) -------------------------------

# The tables are set up so that they automatically 
# generate a primary key if we don't insert one explicitly
con <- DBI::dbConnect(RSQLite::SQLite(), "data/variants.sqlite")
p <- data.frame(ethnicity = "TEST")
DBI::dbAppendTable(con, "Patient", p) # success!

# We can retrieve the patient_id that was generated, and use it to find the patient record
auto_patient_id <- DBI::dbGetQuery(con, "SELECT last_insert_rowid()")$`last_insert_rowid()`
DBI::dbGetQuery(con, glue::glue(
  "SELECT * FROM Patient WHERE patient_id = {auto_patient_id}"))

DBI::dbDisconnect(con)

# the columns of the new data are:
# NHI, variant_code, gene_name, vaf, pop_freq, tumour_type

new_records <- read.csv("data/new_records.csv")

# no ethnicity (NULL)
new_patients <- data.frame(patient_id = new_records$NHI, 
                           cancer_type = new_records$tumour_type) 

# TODO: check if the patient is in the table
# TODO: if new patient then insert row, retrieve patient_id

# no variant_id
new_variants <- data.frame(name = new_records$variant_code) 
new_variants <- cbind(new_variants, split_variant_name(new_variants$name))

# TODO: check if the variant is in the table
# TODO: if new variant then insert row, retrieve the generated variant_id

# no gene_id
new_genes <- data.frame(name = new_records$gene_name) 

# TODO: check if the gene is in the table
# TODO: if new gene then insert row, retrieve the generated gene_id

# no gene_variant_id, gene_id or variant_id
new_gene_variants <- data.frame(pop_freq = new_records$pop_freq) 

# TODO: use gene_id and variant_id in find_gene_variant() to check if the gene_variant is in the table
# TODO: if new gene_variant then insert row, retrieve the gene_variant_id

# no gene_variant_id
new_patient_gene_variants <- data.frame(patient_id = new_records$NHI,
                                        vaf = new_records$vaf)

# TODO: if it's an existing patient, check if they already have that gene_variant recorded
# TODO: if new patient_gene_variant then insert row

# Exploring ---------------------------------------------------------------

# # convert one_table to a tibble and arrange by patient_id
# one_table <- one_table %>% 
#   tibble::as_tibble() %>% 
#   dplyr::arrange(patient_id)
# 
# # try out the function for splitting variant names
# split_variant_name(one_table$variant_name)

# Invalid missense variant nomenclature examples for G13D:
# '13D', 'G 13 D', '13>GD', etc
# 'KRAS: c.38G>A','p.Gly13Asp'

# Invalid gene nomenclature examples for KRAS:
# 'C-K-RAS', 'CFC2', 'K-RAS2A', 'K-RAS2B'

# vaf:
# the proportion of DNA molecules in a 
# sample that carry a specific genetic variant.

# pop_freq:
# proportion of individuals in a given population 
# who carry a specific genetic variant.







